import { create } from 'zustand';

type Language = 'az' | 'en';

interface LanguageStore {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, substitutions?: Record<string, string>) => string;
}

// This is a placeholder for translations
// In a real app, you would import these from JSON files or fetch from API
const translations = {  az: {
    'common.learnMore': 'Daha ətraflı',
    'common.loading': 'Yüklənir...',
    'common.backToList': 'Siyahıya qayıt',
    'home.hero.title': 'BDU Tələbə Elmi-Texniki Yaradıcılıq Mərkəzi',
    'home.hero.subtitle': 'İnnovasiya, yaradıcılıq və elmi araşdırmaların mərkəzi',
    'home.hero.cta': 'İdeyalarınızı təqdim edin',
    'home.ideas.title': 'İnnovativ İdeyalar',
    'home.ideas.viewAll': 'Hamısına baxın',
    'home.achievements.title': 'Nailiyyətlər',
    'home.achievements.viewAll': 'Hamısına baxın',
    'home.clubs.title': 'Dərnəklər',
    'home.clubs.viewAll': 'Hamısına baxın',
    'home.blog.title': 'Xəbərlər və Məqalələr',
    'home.blog.viewAll': 'Hamısına baxın',
    'nav.home': 'Ana səhifə',    'nav.ideas': 'İdeyalar',
    'nav.achievements': 'Nailiyyətlər',
    'nav.clubs': 'Dərnəklər',
    'nav.blog': 'Bloq',
    'nav.about': 'Haqqımızda',
    'nav.submit': 'İdeyanı göndər',
    'ideas.title': 'İnnovativ İdeyalar',
    'ideas.subtitle': 'BDU tələbələrinin yaradıcı və innovativ ideyalarını araşdırın',
    'ideas.searchPlaceholder': 'Axtarış...',
    'ideas.showing': 'Göstərilir',
    'ideas.results': 'nəticələr',    'ideas.noResults': 'Nəticə tapılmadı',
    'ideas.tryAdjusting': 'Filtrinizi tənzimləməyə və ya axtarış sorğunuzu dəyişdirməyə çalışın',
    'ideas.resetFilters': 'Filtrləri sıfırlamaq',
    'ideas.notFound': 'İdeya tapılmadı',
    'ideas.noIdeaWithId': 'Bu ID ilə heç bir ideya mövcud deyil',
    'ideas.backToIdeas': 'İdeyalara qayıt',
    'ideas.projectDetails': 'Layihə təfərrüatları',
    'ideas.technologies': 'Texnologiyalar',
    'ideas.teamSize': 'Komanda ölçüsü',
    'ideas.duration': 'Müddət',
    'ideas.months': 'ay',
    'ideas.people': 'nəfər',
    'ideas.currentPhase': 'Cari mərhələ',    'ideas.upvotes': 'dəstək',
    'ideas.discuss': 'Müzakirə et',
    'achievements.title': 'Nailiyyətlər',
    'achievements.subtitle': 'BDU Tələbə Elmi-Texniki Yaradıcılıq Mərkəzinin mühüm mükafatları və nailiyyətləri',
    'achievements.searchPlaceholder': 'Nailiyyətləri axtar...',
    'achievements.category': 'Kateqoriya',
    'achievements.year': 'İl',
    'achievements.resetFilters': 'Filtrləri sıfırla',
    'achievements.showing': 'Göstərilir',    'achievements.results': 'nəticələr',
    'achievements.noResults': 'Nəticə tapılmadı',
    'achievements.tryAdjusting': 'Filtrinizi tənzimləməyə və ya axtarış sorğunuzu dəyişdirməyə çalışın',
    'submit.title': 'İdeyanızı təqdim edin',
    'submit.subtitle': 'Yeni və innovativ ideyanızı bizimlə bölüşün və onu reallığa çevirmək üçün dəstək alın',
    'submit.basicInfo': 'Əsas məlumat',
    'submit.ideaTitle': 'İdeya başlığı',
    'submit.category': 'Kateqoriya',
    'submit.selectCategory': 'Bir kateqoriya seçin',
    'submit.ideaDetails': 'İdeya təfərrüatları',
    'submit.briefDescription': 'Qısa təsvir',
    'submit.descriptionPlaceholder': 'İdeyanızın qısa təsvirini daxil edin...',
    'submit.minChars': 'Minimum {{count}} simvol',
    'submit.problemStatement': 'Problem təsviri',
    'submit.problemPlaceholder': 'İdeyanızın həll etdiyi problemi təsvir edin...',
    'submit.proposedSolution': 'Təklif olunan həll',
    'submit.solutionPlaceholder': 'Problemi həll etmək üçün təklif etdiyiniz həlli təsvir edin...',
    'submit.targetAudience': 'Hədəf auditoriya',
    'submit.audiencePlaceholder': 'İdeyanızın kimə yönəldiyini qeyd edin',
    'submit.technologies': 'Texnologiyalar',
    'submit.technologiesPlaceholder': 'Vergüllə ayrılmış texnologiyalar və alətlər',
    'submit.teamMembers': 'Komanda üzvləri',
    'submit.teamPlaceholder': 'Layihənizdə işləyən digər komanda üzvlərinin adlarını daxil edin',
    'submit.contactInfo': 'Əlaqə məlumatı',
    'submit.email': 'E-poçt',
    'submit.phone': 'Telefon nömrəsi',
    'submit.attachments': 'Əlavələr',
    'submit.uploadFiles': 'Faylları yükləyin',
    'submit.dragDrop': 'və ya faylları buraya sürükləyin',
    'submit.allowedFiles': 'PNG, JPG, GIF, PDF və ya Word sənədləri - max 5MB',
    'submit.termsText': 'İdeyanızı təqdim etməklə, BDU Tələbə Elmi-Texniki Yaradıcılıq Mərkəzinin şərtlərini qəbul edirsiniz',
    'submit.submitting': 'Təqdim edilir...',
    'submit.submitIdea': 'İdeyanı təqdim edin',
    'submit.successTitle': 'İdeyanız uğurla təqdim edildi!',
    'submit.successMessage': 'İdeyanızı nəzərdən keçirəcəyik və tezliklə sizinlə əlaqə saxlayacağıq.',
    'submit.submitAnother': 'Başqa bir ideya təqdim edin',
    'submit.backToHome': 'Ana səhifəyə qayıt',
    'submit.error': 'İdeyanızı təqdim edərkən bir xəta baş verdi. Zəhmət olmasa bir az sonra cəhd edin.',
    'submit.validation.titleRequired': 'İdeya başlığı tələb olunur',
    'submit.validation.categoryRequired': 'Kateqoriya seçimi tələb olunur',
    'submit.validation.descriptionRequired': 'Təsvir tələb olunur',
    'submit.validation.descriptionMin': 'Təsvir ən azı 50 simvol olmalıdır',
    'submit.validation.problemRequired': 'Problem təsviri tələb olunur',
    'submit.validation.solutionRequired': 'Təklif olunan həll tələb olunur',
    'submit.validation.emailRequired': 'E-poçt ünvanı tələb olunur',    'submit.validation.emailValid': 'Düzgün e-poçt ünvanı daxil edin',
    'submit.validation.fileSize': 'Fayl 5MB-dən kiçik olmalıdır',
    'submit.validation.fileType': 'Yalnız şəkillər, PDF və Word sənədlərinə icazə verilir',
    'ideas.pageTitle': 'İnnovativ İdeyalar',
    'ideas.pageSubtitle': 'BDU tələbələrinin innovativ və yaradıcı ideyaları ilə tanış olun',
    'ideas.submitYourIdea': 'Öz ideyanızı təqdim edin',
    // 'ideas.searchPlaceholder': 'İdeyaları axtarın...',
    'ideas.category': 'Kateqoriya',
    'ideas.status': 'Status',
    'ideas.sortBy': 'Çeşidləmə',
    'ideas.newest': 'Ən yeni',
    'ideas.oldest': 'Ən köhnə',
    'ideas.alphabetical': 'Əlifba sırası ilə',
    // 'ideas.showing': 'Göstərilir',
    // 'ideas.results': 'nəticələr',
    
    // Clubs page translations
    'clubs.pageTitle': 'Dərnəklər və Tədqiqat Qrupları',
    'clubs.pageSubtitle': 'Maraqlarınıza uyğun dərnək tapın və həmfikir tələbələrlə əlaqə qurun',
    'clubs.searchPlaceholder': 'Dərnəkləri axtarın...',
    'clubs.category': 'Kateqoriya',
    'clubs.sortBy': 'Çeşidləmə',
    'clubs.alphabetical': 'Əlifba sırası ilə',
    'clubs.mostMembers': 'Ən çox üzvlərə görə',
    'clubs.newest': 'Ən yeni',
    'clubs.resetFilters': 'Filtrləri sıfırla',
    'clubs.showing': 'Göstərilir',
    'clubs.results': 'nəticələr',
    'clubs.noResults': 'Nəticə tapılmadı',
    'clubs.tryAdjusting': 'Filtrinizi tənzimləməyə və ya axtarış sorğunuzu dəyişdirməyə çalışın',
    'clubs.notFound': 'Dərnək tapılmadı',
    'clubs.notFoundDesc': 'Axtardığınız dərnək mövcud deyil və ya silinib.',
    'clubs.about': 'Dərnək haqqında',
    'clubs.achievements': 'Nailiyyətlər',
    'clubs.upcomingEvents': 'Gələcək tədbirlər',
    'clubs.details': 'Dərnək məlumatları',
    'clubs.members': 'Üzvlər',
    'clubs.founded': 'Təsis edilib',
    'clubs.meetings': 'Görüş cədvəli',
    'clubs.location': 'Məkan',
    'clubs.advisor': 'Fakultet məsləhətçisi',
    'clubs.email': 'Əlaqə e-poçtu',
    'clubs.followUs': 'Bizi izləyin',
    'clubs.joinUs': 'Bizə qoşulun',
    'clubs.joinUsDesc': 'Komandamıza qoşulmaq və innovativ layihələr üzərində işləmək istəyirsinizsə, bizimlə əlaqə saxlayın.',
    'clubs.contactUs': 'Bizimlə əlaqə saxlayın',
    
    // Blog page translations
    'blog.pageTitle': 'Bloq və Xəbərlər',
    'blog.pageSubtitle': 'TETYM-in ən son yenilikləri, nailiyyətləri və tədbirləri haqqında məlumat əldə edin',
    'blog.searchPlaceholder': 'Yazıları axtarın...',
    'blog.category': 'Kateqoriya',
    'blog.sortBy': 'Çeşidləmə',
    'blog.newest': 'Ən yeni',
    'blog.oldest': 'Ən köhnə',
    'blog.alphabetical': 'Əlifba sırası ilə',
    'blog.resetFilters': 'Filtrləri sıfırla',
    'blog.showing': 'Göstərilir',
    'blog.results': 'nəticələr',
    'blog.noResults': 'Nəticə tapılmadı',
    'blog.tryAdjusting': 'Filtrinizi tənzimləməyə və ya axtarış sorğunuzu dəyişdirməyə çalışın',
    'blog.notFound': 'Yazı tapılmadı',
    'blog.notFoundDesc': 'Axtardığınız yazı mövcud deyil və ya silinib.',
    'blog.tags': 'Etiketlər',
    'blog.share': 'Paylaş',
    'blog.author': 'Müəllif',
    'blog.authorDesc': 'BDU Tələbə Elmi-Texniki Yaradıcılıq Mərkəzinin üzvü və tədqiqatçı.',
    'blog.relatedPosts': 'Əlaqəli yazılar',
    'blog.stayUpdated': 'Yeniləmələr üçün abunə olun',
    'blog.subscribeDesc': 'Ən son yenilikləri, tədbirləri və texniki məqalələri əldə etmək üçün bülletenimizə abunə olun.',
    'blog.emailPlaceholder': 'E-poçt ünvanınızı daxil edin',
    'blog.subscribe': 'Abunə ol',
    
    // About page translations
    'about.pageTitle': 'Haqqımızda',
    'about.pageSubtitle': 'BDU Tələbə Elmi-Texniki Yaradıcılıq Mərkəzinin hekayəsi və missiyası',
    'about.ourMissionTitle': 'Missiyamız',
    'about.ourMissionParagraph1': 'BDU Tələbə Elmi-Texniki Yaradıcılıq Mərkəzi (TETYM) tələbələrə innovativ ideyalarını inkişaf etdirmək və texniki layihələrini həyata keçirmək üçün məkan, resurslar və dəstək təmin etməyə həsr olunub.',
    'about.ourMissionParagraph2': 'Biz texniki yaradıcılıq, tədqiqat və innovasiyanı təşviq etməklə, gəncləri gələcəyin texnologiya liderləri olmağa hazırlayırıq.',
    'about.ourHistoryTitle': 'Tariximiz',
    'about.ourHistoryParagraph1': 'TETYM 2020-ci ildə rəqəmsal transformasiyaya və innovasiyaya dəstək vermək məqsədilə yaradılıb. O zamandan bəri biz yüzlərlə tələbənin texniki bacarıqlarını inkişaf etdirməsinə və novator layihələr həyata keçirməsinə kömək etmişik.',
    'about.ourHistoryParagraph2': 'Bu illərdə mərkəzimiz milli və beynəlxalq müsabiqələrdə çoxsaylı mükafatlar qazanmış və Azərbaycan ali təhsil müəssisələrində texniki innovasiya mərkəzi kimi tanınmışdır.',
    'about.ourTeamTitle': 'Komandamız',
    'about.ourTeamSubtitle': 'TETYM-in uğurlarının arxasında duran insanlarla tanış olun',
    'about.directorTitle': 'Direktor, TETYM',
    'about.researchDirectorTitle': 'Tədqiqat Direktoru',
    'about.innovationLeadTitle': 'İnnovasiya Rəhbəri',
    'about.studentEngagementTitle': 'Tələbə Əlaqələri Rəhbəri',
    'about.teamMember1Bio': 'Dr. Əliyev TETYM-in fəaliyyətlərinə rəhbərlik edir və mərkəzin strateji istiqamətini müəyyənləşdirir.',
    'about.teamMember2Bio': 'Dr. Məmmədova tələbə araşdırma layihələrinə nəzarət edir və elmi-texniki əməkdaşlıqları əlaqələndirir.',
    'about.teamMember3Bio': 'Kamran tələbələrə innovativ ideyalarını inkişaf etdirməkdə və onları real həllərə çevirməkdə kömək edir.',
    'about.teamMember4Bio': 'Səbinə tələbə iştirakını artırmaq və dərnək fəaliyyətlərini əlaqələndirmək üçün proqramlar hazırlayır və həyata keçirir.',
    'about.statStudents': 'Aktiv tələbələr',
    'about.statInnovations': 'İnnovasiya layihələri',
    'about.statClubs': 'Texniki dərnəklər',
    'about.statAwards': 'Mükafatlar',
    'about.contactTitle': 'Bizimlə əlaqə saxlayın',
    'about.contactSubtitle': 'Sualınız var? TETYM-lə əlaqə saxlayın',
    'about.address': 'Ünvan',
    'about.addressLine1': 'Bakı Dövlət Universiteti',
    'about.addressLine2': 'Akademik Zahid Xəlilov küçəsi, 23',
    'about.addressLine3': 'AZ1148, Bakı, Azərbaycan',
    'about.email': 'E-poçt',
    'about.phone': 'Telefon',
  },  en: {
    'common.learnMore': 'Learn More',
    'common.loading': 'Loading...',
    'common.backToList': 'Back to List',
    'home.hero.title': 'BSU Student Scientific-Technical Creativity Center',
    'home.hero.subtitle': 'Center for innovation, creativity, and scientific research',
    'home.hero.cta': 'Submit Your Ideas',
    'home.ideas.title': 'Innovative Ideas',
    'home.ideas.viewAll': 'View All',
    'home.achievements.title': 'Achievements',
    'home.achievements.viewAll': 'View All',
    'home.clubs.title': 'Clubs',
    'home.clubs.viewAll': 'View All',
    'home.blog.title': 'News & Articles',
    'home.blog.viewAll': 'View All',
    'nav.home': 'Home',
    'nav.ideas': 'Ideas',
    'nav.achievements': 'Achievements',
    'nav.clubs': 'Clubs',    'nav.blog': 'Blog',
    'nav.about': 'About Us',
    'nav.submit': 'Submit Idea',
    'ideas.title': 'Innovative Ideas',
    'ideas.subtitle': 'Explore creative and innovative ideas from BSU students',
    'ideas.searchPlaceholder': 'Search...',
    'ideas.showing': 'Showing',
    'ideas.results': 'results',    'ideas.noResults': 'No results found',
    'ideas.tryAdjusting': 'Try adjusting your filter or changing your search query',
    'ideas.resetFilters': 'Reset Filters',
    'ideas.notFound': 'Idea Not Found',
    'ideas.noIdeaWithId': 'No idea exists with this ID',
    'ideas.backToIdeas': 'Back to Ideas',
    'ideas.projectDetails': 'Project Details',
    'ideas.technologies': 'Technologies',
    'ideas.teamSize': 'Team Size',
    'ideas.duration': 'Duration',
    'ideas.months': 'months',
    'ideas.people': 'people',
    'ideas.currentPhase': 'Current Phase',    'ideas.upvotes': 'upvotes',
    'ideas.discuss': 'Discuss',
    'achievements.title': 'Achievements',
    'achievements.subtitle': 'Significant awards and accomplishments of the BSU Student Scientific-Technical Creativity Center',
    'achievements.searchPlaceholder': 'Search achievements...',
    'achievements.category': 'Category',
    'achievements.year': 'Year',
    'achievements.resetFilters': 'Reset Filters',
    'achievements.showing': 'Showing',    'achievements.results': 'results',
    'achievements.noResults': 'No results found',
    'achievements.tryAdjusting': 'Try adjusting your filter or changing your search query',
    'submit.title': 'Submit Your Idea',
    'submit.subtitle': 'Share your new and innovative idea with us and get support to make it a reality',
    'submit.basicInfo': 'Basic Information',
    'submit.ideaTitle': 'Idea Title',
    'submit.category': 'Category',
    'submit.selectCategory': 'Select a category',
    'submit.ideaDetails': 'Idea Details',
    'submit.briefDescription': 'Brief Description',
    'submit.descriptionPlaceholder': 'Enter a short description of your idea...',
    'submit.minChars': 'Minimum {{count}} characters',
    'submit.problemStatement': 'Problem Statement',
    'submit.problemPlaceholder': 'Describe the problem your idea solves...',
    'submit.proposedSolution': 'Proposed Solution',
    'submit.solutionPlaceholder': 'Describe your proposed solution to address the problem...',
    'submit.targetAudience': 'Target Audience',
    'submit.audiencePlaceholder': 'Indicate who your idea is aimed at',
    'submit.technologies': 'Technologies',
    'submit.technologiesPlaceholder': 'Comma-separated technologies and tools',
    'submit.teamMembers': 'Team Members',
    'submit.teamPlaceholder': 'Enter the names of other team members working on your project',
    'submit.contactInfo': 'Contact Information',
    'submit.email': 'Email',
    'submit.phone': 'Phone Number',
    'submit.attachments': 'Attachments',
    'submit.uploadFiles': 'Upload files',
    'submit.dragDrop': 'or drag and drop files here',
    'submit.allowedFiles': 'PNG, JPG, GIF, PDF or Word documents - max 5MB',
    'submit.termsText': 'By submitting your idea, you agree to the terms and conditions of the BSU Student Scientific-Technical Creativity Center',
    'submit.submitting': 'Submitting...',
    'submit.submitIdea': 'Submit Idea',
    'submit.successTitle': 'Your Idea Was Successfully Submitted!',
    'submit.successMessage': 'We will review your idea and get back to you soon.',
    'submit.submitAnother': 'Submit Another Idea',
    'submit.backToHome': 'Back to Home',
    'submit.error': 'An error occurred while submitting your idea. Please try again later.',
    'submit.validation.titleRequired': 'Idea title is required',
    'submit.validation.categoryRequired': 'Category selection is required',
    'submit.validation.descriptionRequired': 'Description is required',
    'submit.validation.descriptionMin': 'Description must be at least 50 characters',
    'submit.validation.problemRequired': 'Problem statement is required',
    'submit.validation.solutionRequired': 'Proposed solution is required',    'submit.validation.emailRequired': 'Email address is required',
    'submit.validation.emailValid': 'Please enter a valid email address',
    'submit.validation.fileSize': 'File must be less than 5MB',
    'submit.validation.fileType': 'Only images, PDFs, and Word documents are allowed',
    'ideas.pageTitle': 'Innovative Ideas',
    'ideas.pageSubtitle': 'Discover innovative and creative ideas from BSU students',
    'ideas.submitYourIdea': 'Submit Your Idea',
    // 'ideas.searchPlaceholder': 'Search ideas...',
    'ideas.category': 'Category',
    'ideas.status': 'Status',
    'ideas.sortBy': 'Sort By',
    'ideas.newest': 'Newest',
    'ideas.oldest': 'Oldest',
    'ideas.alphabetical': 'Alphabetical',
    
    // Clubs page translations
    'clubs.pageTitle': 'Clubs & Research Groups',
    'clubs.pageSubtitle': 'Find a club that matches your interests and connect with like-minded students',
    'clubs.searchPlaceholder': 'Search clubs...',
    'clubs.category': 'Category',
    'clubs.sortBy': 'Sort By',
    'clubs.alphabetical': 'Alphabetical',
    'clubs.mostMembers': 'Most Members',
    'clubs.newest': 'Newest',
    'clubs.resetFilters': 'Reset Filters',
    'clubs.showing': 'Showing',
    'clubs.results': 'results',
    'clubs.noResults': 'No results found',
    'clubs.tryAdjusting': 'Try adjusting your filter or changing your search query',
    'clubs.notFound': 'Club Not Found',
    'clubs.notFoundDesc': 'The club you are looking for does not exist or has been removed.',
    'clubs.about': 'About the Club',
    'clubs.achievements': 'Achievements',
    'clubs.upcomingEvents': 'Upcoming Events',
    'clubs.details': 'Club Details',
    'clubs.members': 'Members',
    'clubs.founded': 'Founded',
    'clubs.meetings': 'Meeting Schedule',
    'clubs.location': 'Location',
    'clubs.advisor': 'Faculty Advisor',
    'clubs.email': 'Contact Email',
    'clubs.followUs': 'Follow Us',
    'clubs.joinUs': 'Join Our Club',
    'clubs.joinUsDesc': 'If you\'re interested in joining our team and working on innovative projects, get in touch with us.',
    'clubs.contactUs': 'Contact Us',
    
    // Blog page translations
    'blog.pageTitle': 'Blog & News',
    'blog.pageSubtitle': 'Stay informed about the latest innovations, achievements, and events at SSTCC',
    'blog.searchPlaceholder': 'Search posts...',
    'blog.category': 'Category',
    'blog.sortBy': 'Sort By',
    'blog.newest': 'Newest',
    'blog.oldest': 'Oldest',
    'blog.alphabetical': 'Alphabetical',
    'blog.resetFilters': 'Reset Filters',
    'blog.showing': 'Showing',
    'blog.results': 'results',
    'blog.noResults': 'No results found',
    'blog.tryAdjusting': 'Try adjusting your filter or changing your search query',
    'blog.notFound': 'Post Not Found',
    'blog.notFoundDesc': 'The post you are looking for does not exist or has been removed.',
    'blog.tags': 'Tags',
    'blog.share': 'Share',
    'blog.author': 'Author',
    'blog.authorDesc': 'Member and researcher at the BSU Student Scientific-Technical Creativity Center.',
    'blog.relatedPosts': 'Related Posts',
    'blog.stayUpdated': 'Stay Updated',
    'blog.subscribeDesc': 'Subscribe to our newsletter to receive the latest news, events, and technical articles.',
    'blog.emailPlaceholder': 'Enter your email address',
    'blog.subscribe': 'Subscribe',
    
    // About page translations
    'about.pageTitle': 'About Us',
    'about.pageSubtitle': 'The story and mission of BSU Student Scientific-Technical Creativity Center',
    'about.ourMissionTitle': 'Our Mission',
    'about.ourMissionParagraph1': 'The BSU Student Scientific-Technical Creativity Center (SSTCC) is dedicated to providing students with the space, resources, and support to develop their innovative ideas and bring their technical projects to life.',
    'about.ourMissionParagraph2': 'By fostering technical creativity, research, and innovation, we prepare young people to become the technology leaders of tomorrow.',
    'about.ourHistoryTitle': 'Our History',
    'about.ourHistoryParagraph1': 'SSTCC was established in 2020 with the aim of supporting digital transformation and innovation. Since then, we have helped hundreds of students develop their technical skills and implement groundbreaking projects.',
    'about.ourHistoryParagraph2': 'Over the years, our center has won numerous awards in national and international competitions and has been recognized as a hub for technical innovation in Azerbaijani higher education institutions.',
    'about.ourTeamTitle': 'Our Team',
    'about.ourTeamSubtitle': 'Meet the people behind the success of SSTCC',
    'about.directorTitle': 'Director, SSTCC',
    'about.researchDirectorTitle': 'Research Director',
    'about.innovationLeadTitle': 'Innovation Lead',
    'about.studentEngagementTitle': 'Student Engagement Lead',
    'about.teamMember1Bio': 'Dr. Aliyev oversees the activities of SSTCC and defines the strategic direction of the center.',
    'about.teamMember2Bio': 'Dr. Mammadova supervises student research projects and coordinates scientific and technical collaborations.',
    'about.teamMember3Bio': 'Kamran helps students develop their innovative ideas and transform them into real-world solutions.',
    'about.teamMember4Bio': 'Sabina develops and implements programs to increase student participation and coordinate club activities.',
    'about.statStudents': 'Active Students',
    'about.statInnovations': 'Innovation Projects',
    'about.statClubs': 'Technical Clubs',
    'about.statAwards': 'Awards',
    'about.contactTitle': 'Get in Touch',
    'about.contactSubtitle': 'Have a question? Contact the SSTCC',
    'about.address': 'Address',
    'about.addressLine1': 'Baku State University',
    'about.addressLine2': 'Academician Zahid Khalilov Street, 23',
    'about.addressLine3': 'AZ1148, Baku, Azerbaijan',
    'about.email': 'Email',
    'about.phone': 'Phone',
  }
};

// Function to do variable interpolation in translations
// Example: "Hello {name}" with {name: "World"} becomes "Hello World"
function interpolate(text: string, substitutions?: Record<string, string>): string {
  if (!substitutions) return text;
  
  return Object.entries(substitutions).reduce(
    (acc, [key, value]) => acc.replace(new RegExp(`{${key}}`, 'g'), value),
    text
  );
}

export const useLanguage = create<LanguageStore>((set, get) => ({
  language: 'en', // Default language
  setLanguage: (lang: Language) => set({ language: lang }),  t: (key: string, substitutions?: Record<string, string>) => {
    const { language } = get();
    const langTranslations = translations[language] as Record<string, string>;
    const translation = langTranslations[key] || key;
    return interpolate(translation, substitutions);
  }
}));
